version: '3.8'

services:
    db:
        image: mysql
        platform: linux/x86_64
        container_name: csd-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            # * this will create a databse and user, so make .sql files do not have conflicting create database/user commands
            # * do not create database/user here if done so in .sql files
            # MYSQL_DATABASE: whatabook
            MYSQL_ROOT_PASSWORD: docker
            # * if using a .sql file for init, make sure to grant all permissions to the remote user as well as localhost
            MYSQL_USER: whatabook_user
            MYSQL_PASSWORD: MySQL8IsGreat!
        volumes:
             - ./data:/var/lib/mysql/
             - ./init-db.d/:/docker-entrypoint-initdb.d/
        ports:
            - 3306:3306
